name: CI Pipeline

on:
  pull_request:
    branches:
      - main  # Passe den Branch an, auf dem du arbeiten möchtest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkt deinen Code aus
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Wähle die Python-Version, die du verwendest
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Installiere deine Abhängigkeiten
        pip install pytest pytest-cov pytest-xdist
    - name: Run tests with coverage and parallelization
      run: |
        pytest -n auto --cov=note_api --cov-report=term-missing