#name: Example workflow for Docker using Snyk
#on: push
#jobs:
#  security:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Run Snyk to check Docker image for vulnerabilities
#      uses: snyk/actions/docker@master
#      env:
#        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#      with:
#        image: your/image-to-test

image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - security

build:
  stage: build
  script:
    # Baue das Docker-Image aus dem Dockerfile
    - docker build -t my-app:latest .

test:
  stage: test
  script:
    # Führe Tests im Docker-Container aus (z.B. mit pytest)
    - docker run --rm my-app:latest pytest

security:
  stage: security
  script:
    # Scanne das Docker-Image mit Snyk
    - snyk test --docker my-app:latest --all-sub-projects