name: CI Pipeline Docker

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # DOCKERHUB_USERNAME muss als Secret hinzugef端gt werden
          password: ${{ secrets.DOCKERHUB_TOKEN }} # DOCKERHUB_TOKEN muss als Secret hinzugef端gt werden
          # daf端r muss man sich bei Docker Hub anmelden und mit GitHub verbinden, dann dort ein Access Token erstellen
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest # Hier muss man ggf seinen eigenen Benutzernamen einf端gen
