name: CI Pipeline Snyk

on: push

jobs:
  build:
    runs-on: ubuntu-latest  # Führe auf einem Ubuntu-Läufer aus

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Klone das Repository

      - name: Build Docker Image
        run: docker build -t my-app:latest .  # Baue das Docker-Image aus dem Dockerfile

      - name: Run Tests
        run: docker run --rm my-app:latest pytest  # Führe die Tests im Docker-Container aus

      - name: Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Verwende das Snyk-Token aus den GitHub-Secrets
        run: snyk test --docker my-app:latest  # Scanne das Docker-Image mit Snyk


#name: Example workflow for Docker using Snyk
#on: push
#jobs:
#  security:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Run Snyk to check Docker image for vulnerabilities
#      uses: snyk/actions/docker@master
#      env:
#        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#      with:
#        image: your/image-to-test