name: DevSecOpsTask1

#Trigger workflow on pull requests and push
on:
  pull_request:
  push:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest      
        
    steps:
      
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          #Caching packages dependencies
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - run: echo "Python has been set up."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip install -r requirements-dev.txt
      - run: echo "Dependencies have been installed."

      - name: Run tests with pytest
        #Using all available CPU-cores with -n auto
        #Measure code coverage during the test with --cov
        run: pytest -n auto --cov=note_api tests/ --cov-report=xml
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@v1
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - run: echo "Pytest has been executed. Job status is ${{ job.status }}."
